### ISSUE TITLE
Bug? Templates not working . . . 

### ISSUE THREAD

**Issue by JadedChara** [frissyn/Reflux#14]
Out of curiosity, I tried the Jett Black template, but it said the badge could not be applied. Any idea what causes this?

**Comment by frissyn** [comment]
@CharaHarimata Not sure what the issue could be, I'll get to troubleshooting as soon as I can, thanks for reporting!

**Comment by JadedChara** [comment]
Thank you for quick reply! I haven't tried the actual framework as of yet, just the min.js examples in the theme folder.

**Comment by ShuchirJ** [comment]
Hey @CharaHarimata !
Are you on Replit's homepage or inside of the editor?
If you're on the homepage, is it saying anything about topbuttons?

**Comment by ShuchirJ** [comment]
Hey,
Apologies I didn't see your last message.
The examples which you are referring to are outdated and no longer work due to changes on Replit's side.
Here's a hacky workaround that we're still working on-

- Install `reflux/engine/reflux.min.js` as a bookmarklet
- Visit https://market.reflux.repl.co and click the theme of your choice
- It will return a 404 not found, just copy the URL part after `https://market.reflux.repl.co/theme/` (We are working on this, it's under construction)
- Go to Replit
- Click on the bookmarklet
- Paste the code you just copied

If you're on Replit's homepage, it will error about something called topbuttons. We are working on this, just ignore it, it will be applied regardless.

**Comment by JadedChara** [comment]
Thank you! That worked. It does seem to be returning a minor error (unable to utilize clicks), but it still applies the theme.

**Comment by JadedChara** [comment]
Just out of curiosity, how do the referral tokens work? Can one use their own theme in place of it, or are the mechanics of it also made problematic by Repl.it's update? I tried logging in to the market, but the site returns 503.

**Comment by frissyn** [comment]
Referral codes are a way of identifying themes in the API. There currently isn't a way to use themes without uploading them and getting a code.

**Comment by ShuchirJ** [comment]
Like frissyn said, referral codes are like an id, they identify which theme to download from the API. There currently isn’t a way to use a theme without a referral code, but it is being added in our extension which will be released soon.
